### ISSUE TITLE
Binding model properly

### ISSUE THREAD

**Issue by atullal** [Dornhoth/control-value-accessor#1]
Hi,
In this method that you have implemented. The onChange method you are calling should use this.selectedItems as argument instead of this.items. Otherwise, the model is not binding properly in the parent component.

```
onItemClick(item: ListItem) {
    if (!this.disabled) {
      const found = this.isItemAlreadySelected(item);
      if (!found) {
        this.select(item);
      } else {
        this.unselect(item);
      }
      this.onChange(this.items); // This should be this.onChange(this.selectedItems);
    }
  }
```

**Comment by Dornhoth** [comment]
Hi,
thanks for pointing it out, I have fixed it
